apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "free-domain.fullname" . }}
  labels:
    {{- include "free-domain.labels" . | nindent 4 }}
data:
  config.yaml: | {{ toYaml .Values.freeDomain | nindent 4 }}
